<?php

/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\LucideIcons;
use Hyva\Theme\ViewModel\BlockJsDependencies;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Block\Product\View;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Pricing\Render;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong
// phpcs:disable Generic.WhiteSpace.ScopeIndent

/** @var View $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var LucideIcons $lucideIcons */
$lucideIcons = $viewModels->require(LucideIcons::class);

/** @var SvgIcons $hyvaicons */
$hyvaicons = $viewModels->require(SvgIcons::class);

$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);

/** @var Magento\Catalog\Model\Product $product */
if (! ($product = $block->getData('product'))) {
    return;
}
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$showAddToCompare = $compareViewModel->showInProductList();
$viewIsGrid = $viewMode === 'grid';
$productType = $product->getTypeId();
$isProductGroupedOrBundle = $productType === 'bundle' || $productType === "grouped";
$productId = $product->getId();
$options   = $productOptionsViewmodel->getOptionsData($product);

$hideDetails       = $block->getData('hide_details') ?: false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];
$productName = $catalogOutputHelper->productAttribute($product, $product->getName(), 'name');

// Calcola il prezzo originale e lo sconto
$priceInfo = $product->getPriceInfo();
$regularPrice = $priceInfo->getPrice('regular_price')->getAmount()->getValue();
$finalPrice = $priceInfo->getPrice('final_price')->getAmount()->getValue();
$specialPrice = $product->getSpecialPrice();

// Determina se c'è uno sconto
$hasDiscount = $finalPrice < $regularPrice && $regularPrice > 0;
$discountPercentage = 0;

if ($hasDiscount) {
    $discountPercentage = round((($regularPrice - $finalPrice) / $regularPrice) * 100);
}


$priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);

// Ensure the required JS is rendered on the page
$viewModels->require(BlockJsDependencies::class)->setBlockTemplateDependency($block, 'Magento_Catalog::product/list/js/price-box.phtml');

?>

<?php if ($product->isSaleable()): ?>
    <!-- FORM -->
    <form method="post"
        action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
        class="border relative item product product-item product_addtocart_form card card-interactive flex flex-col w-full h-full bg-white hover:bg-white p-1.5 rounded-none"
        <?php if ($product->getOptions()): ?>
        enctype="multipart/form-data"
        <?php endif; ?>
        <?php foreach ($block->getData('product_data_attributes') ?? [] as $attribute => $include): ?>
        <?php if ($include): ?>
        <?php /** Append data-* attributes based on layout XML arguments */ ?>
        <?= $escaper->escapeHtml(sprintf('data-%s', $attribute)); ?>="<?= $escaper->escapeHtmlAttr($product->getData($attribute)); ?>"
        <?php endif; ?>
        <?php endforeach; ?>>
        <?=
        /** @noEscape */
        $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="product" value="<?= (int)$productId ?>">
        <?php foreach ($options as $optionItem): ?>
            <input type="hidden"
                name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
        <?php endforeach; ?>
    <?php else: ?>
        <div class="border relative item product product-item card card-interactive flex flex-col justify-between w-full h-full bg-white hover:bg-white p-1.5 rounded-none">
            <?php foreach ($block->getData('product_data_attributes')  ?? [] as $attribute => $include): ?>
                <?php if ($include): ?>
                    <?php /** Append data-* attributes based on layout XML arguments */ ?>
                    <?= $escaper->escapeHtml(sprintf('data-%s', $attribute)); ?>="<?= $escaper->escapeHtmlAttr($product->getData($attribute)); ?>"
                <?php endif; ?>
            <?php endforeach; ?>
            <!-- END FORM/DIV  -->
        </div>
        >
    <?php endif; ?>
    <?php /* Product Image */ ?>
    <?php if ($blockImage = $block->getImage($product, $imageDisplayArea)): ?>
        <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
            title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
            class="product photo product-item-photo block mx-auto mb-3 <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:shrink-0' ?>"
            tabindex="-1">
            <?= $blockImage
                ->setTemplate('Magento_Catalog::product/list/image.phtml')
                ->setData('custom_attributes', $imageCustomAttributes)
                ->setProductId($productId)
                ->toHtml();
            ?>
        </a>
    <?php endif; ?>
    <div class="product-info flex flex-col grow <?= $viewIsGrid ? '' : 'md:pl-5 md:w-4/6' ?>">
        <div class="mb-1 items-center justify-center  text-sm text-start text-black px-4 <?= $viewIsGrid ? '' : 'md:text-left' ?>">
            <a
                class="product-item-link"
                href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                <?= /* @noEscape */ $productName ?>
            </a>
        </div>
        <?php if ($product->isAvailable() && !$hideDetails): ?>
            <?= $block->getProductDetailsHtml($product) ?>
        <?php endif; ?>

        <?php if ($showDescription): ?>
            <div class="mt-2 mb-1 items-center justify-center text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
            </div>
        <?php endif; ?>

        <?php if ($isProductGroupedOrBundle): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the options chosen on the product page')) ?>
            </span>
        <?php endif; ?>

        <div class="flex items-center justify-between px-4 mt-auto mb-2">
            <div class="flex-1 flex items-center">
                <div class="price-stack leading-none"
                    x-data="initPriceBox()"
                    x-defer="intersect"
                    @update-prices-<?= (int)$productId ?>.window="updatePrice($event.detail);">
                    <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
                </div>
            </div>

            <?php if ($product->isSaleable()): ?>
                <?php if ($isProductGroupedOrBundle): ?>
                    <a
                        href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                        class="btn btn-primary text-sm <?= $viewIsGrid ? 'me-auto' : 'me-auto md:me-0' ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Configure %1 on the product page', $productName)) ?>">
                        <?= $lucideIcons->pencilHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                        <span class="inline <?= $viewIsGrid ? 'md:hidden lg:inline' : '' ?>">
                            <?= $escaper->escapeHtml(__('Configure')) ?>
                        </span>
                    </a>
                <?php else: ?>
                           <button
                                class="border-orange w-auto py-1.5 px-3.5 btn btn-primary justify-center text-sm <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>"
                                title="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>"
                                data-addto="cart">
                                <span class="addtocart-content addtocart-purchase hidden sm:flex">
                                    <?= $escaper->escapeHtml(__('Acquista')) ?>
                                </span>

                                <div class="addtocart-content addtocart-svg sm:hidden"><?= $hyvaicons->addtoHtml('', 24, 24) ?></div>
                            </button>
                <?php endif; ?>

            <?php else: ?>
                <div class="<?= $viewIsGrid ? 'me-auto' : 'me-auto md:me-0' ?>">
                    <?= $block->getChildBlock('stockstatus')->setData('product', $product)->toHtml() ?>
                </div>
            <?php endif; ?>

        </div>
        <div class="flex flex-row justify-between px-2 h-7">
            <?php if ($hasDiscount && $discountPercentage > 0): ?>
                <div class="flex items-center justify-center h-7 text-sm font-semibold  bg-secondary text-white w-2/3 mr-1">
                    Sconto -<?= (int)$discountPercentage ?>%
                </div>
            <?php else: ?>
                <div class="flex items-center justify-center h-7 text-sm font-semibold  bg-secondary text-white w-2/3 mr-1">
                    Sconto -28%
                </div>
            <?php endif; ?>
            <div class="flex items-center justify-center h-7 text-sm font-semibold  bg-[#5DB95D] text-white w-1/3">
                HOT
            </div>
        </div>
    </div>
    <?php if ($product->isSaleable()): ?>
    </form>
<?php else: ?>
    </div>
<?php endif; ?>